repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: pre-push
        name: pre-push
        entry: pytest
        args: [-v]
        language: system
        stages: [pre-push]
